name: Deploy to LWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.rolandoff.com #${{ secrets.FTP_SERVER }}
        username: rolando@rolandoff.com #${{ secrets.FTP_USERNAME }}
        password: Antibes@10! #${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftps
        local-dir: ./
        server-dir: /public_html/
        log-level: verbose  # ← Añade más detalles en los logs

